import { NextResponse } from "next/server";
import { z } from "zod";
import { getContactContext } from "@/lib/contact-context";
import { openRouterJson } from "@/lib/openrouter";
import { callCardPrompt } from "@/lib/prompts/call-card";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";

const fallback = (context: NonNullable<Awaited<ReturnType<typeof getContactContext>>>) => ({ lead_category: context.company?.buyer_partner_competitor_status ?? "Needs review", fit_score: Number(context.company?.fit_score ?? 0), company_summary: context.company?.industry_auto_classified ? `${context.company.company_name} is classified as ${context.company.industry_auto_classified}.` : "No verified company summary is available.", why_this_company: "CSV signals indicate this prospect may be relevant to customer-operations conversations.", best_gnani_angle: "Start with call automation, agent productivity, or QA visibility.", recommended_products: ["AI Voice Agents", "Agent Assist", "Conversation Analytics"], cold_call_opener: `Hi ${context.contact.first_name || "there"}, this is Sharath from gnani.ai. I’m following up after CCW Las Vegas. Is improving call automation or QA visibility a priority for your team?`, personalized_pitch: "We help customer-operations teams reduce repetitive voice work and give agents better call context.", discovery_questions: ["Where does repetitive call volume create the most work today?", "How do you currently monitor quality across calls?"], objection_handles: { send_email: "Absolutely. Before I send it, which area is more relevant: call automation, agent assist, or QA analytics?", not_interested: "Understood. Is it simply not a priority this quarter, or is there another team that owns it?", wrong_person: "Thanks. Who usually owns customer operations or contact-center improvement there?" }, send_email_line: "I’ll keep it brief and focus on the use case most relevant to your team.", meeting_ask: "Would a short 20-minute conversation next week be useful?", demo_use_case: "A CSV-backed view of repetitive call automation and QA opportunities.", source_confidence: "CSV-backed + inferred" });
export async function POST(request: Request) {
  try { const { email } = z.object({ email: z.string().email() }).parse(await request.json()); const context = await getContactContext(email); if (!context) return NextResponse.json({ error: "No contact found for this email." }, { status: 404 }); let card = fallback(context); let model = "rule-based"; try { const result = await openRouterJson<typeof card>(callCardPrompt(context), 700); card = result.data; model = result.model; } catch { /* a safe fallback is intentional */ }
    const admin = createAdminSupabaseClient(); const { data, error } = await admin.from("lead_intelligence_cards").insert({ contact_id: context.contact.id, company_id: context.company?.id ?? null, ...card, recommended_products: card.recommended_products, discovery_questions: card.discovery_questions, objection_handles: card.objection_handles, generated_by_model: model }).select().single(); if (error) throw new Error(error.message); return NextResponse.json({ card: data, fallback: model === "rule-based" }); }
  catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Call-card generation failed." }, { status: 400 }); }
}
