"use client";
import { useState } from "react";
import { FileUp, HardDrive } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PageTitle } from "@/components/page-title";
type Summary = Record<string, string | number | unknown>;
export default function ImportPage() { const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(""); const [summary, setSummary] = useState<Summary | null>(null); const submit = async (kind: "upload" | "local") => { setLoading(kind); try { const response = kind === "local" ? await fetch("/api/import-local-csv", { method: "POST" }) : await fetch("/api/import-leads", { method: "POST", body: (() => { const data = new FormData(); if (file) data.set("file", file); return data; })() }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSummary(body.summary); toast.success("Import completed"); } catch (error) { toast.error(error instanceof Error ? error.message : "Import failed"); } finally { setLoading(""); } }; return <div className="space-y-6"><PageTitle title="Import CSV" subtitle="Lead CSVs stay local and are never committed to Git." /><div className="grid gap-6 lg:grid-cols-2"><Card className="p-5"><FileUp className="mb-4 size-5 text-zinc-400" /><h2 className="font-medium">Upload a CSV</h2><p className="mt-1 text-sm text-zinc-500">Use this in production or when the lead file is outside the workspace.</p><input className="focus-ring mt-5 block w-full border border-zinc-700 bg-zinc-900 p-2 text-sm file:mr-3 file:border-0 file:bg-zinc-100 file:px-2 file:py-1 file:text-xs file:text-zinc-950" type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><Button className="mt-4 w-full" disabled={!file || !!loading} onClick={() => submit("upload")}>{loading === "upload" ? "Importing..." : "Import uploaded CSV"}</Button></Card><Card className="p-5"><HardDrive className="mb-4 size-5 text-zinc-400" /><h2 className="font-medium">Import local CSV</h2><p className="mt-1 text-sm text-zinc-500">Checks `/data/Klenty_Master_Call_List_Clean.csv` first, then the project-root CSV. This is unavailable on Vercel.</p><Button className="mt-5 w-full" disabled={!!loading} onClick={() => submit("local")}>{loading === "local" ? "Importing..." : "Import local CSV"}</Button></Card></div>{summary && <Card className="p-5"><h2 className="font-medium">Import summary</h2><dl className="mt-4 grid gap-px border border-zinc-800 bg-zinc-800 sm:grid-cols-2 lg:grid-cols-4">{["totalRows", "validRows", "duplicateEmails", "missingEmails", "uniqueCompanies", "uniqueDomains", "rowsNeedingReview", "contactsCreated", "contactsUpdated", "companiesCreated", "companiesUpdated"].map((key) => <div key={key} className="bg-zinc-950 p-3"><dt className="text-xs text-zinc-500">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="mono mt-1 text-lg">{String(summary[key] ?? 0)}</dd></div>)}</dl></Card>}</div>; }
