"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, CalendarDays, ChevronRight, Clock3, Filter, Mail, MessageSquareText, RefreshCw, Search, ShieldAlert, Sparkles, Target, Users, X } from "lucide-react";
import type { ReportFilters } from "@/lib/call-analytics";
import type { ConversationCategory, ConversationInsights } from "@/lib/conversation-analytics";
import { CallDetailDrawer, type Drilldown } from "@/components/call-report/call-detail-drawer";

const EMPTY_FILTERS: ReportFilters = {};
const number = (value: number, digits = 0) => new Intl.NumberFormat("en-US", { maximumFractionDigits: digits }).format(value);
const percent = (value: number, digits = 0) => `${(value * 100).toFixed(digits)}%`;
const duration = (seconds: number) => seconds < 60 ? `${Math.round(seconds)} sec` : `${Math.floor(seconds / 60)}m ${Math.round(seconds % 60)}s`;
const dateTime = (value: string) => new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Kolkata", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const dayInIst = (value: string) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value));
const subtractDays = (day: string, count: number) => { const date = new Date(`${day}T12:00:00Z`); date.setUTCDate(date.getUTCDate() - count); return date.toISOString().slice(0, 10); };

const CATEGORY_STYLE: Record<ConversationCategory, string> = {
  "Follow up now": "border-emerald-400/25 bg-emerald-400/[0.08] text-emerald-300",
  "Referral path": "border-blue-400/25 bg-blue-400/[0.07] text-blue-300",
  Nurture: "border-amber-400/25 bg-amber-400/[0.07] text-amber-300",
  "Competitive context": "border-violet-400/25 bg-violet-400/[0.07] text-violet-300",
  "Closed / suppress": "border-rose-400/25 bg-rose-400/[0.07] text-rose-300",
  "Conversation only": "border-white/10 bg-white/[0.025] text-zinc-400"
};

function Section({ title, detail, children, action }: { title: string; detail?: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="min-w-0 overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0d1014] shadow-[0_24px_80px_rgba(0,0,0,.16)]"><header className="flex flex-col gap-3 border-b border-white/[0.07] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold tracking-tight text-zinc-100">{title}</h2>{detail ? <p className="mt-1 max-w-3xl text-xs leading-5 text-zinc-500">{detail}</p> : null}</div>{action}</header>{children}</section>;
}

function Metric({ label, value, detail, icon: Icon, onClick, emphasis = false }: { label: string; value: string; detail: string; icon: typeof Users; onClick?: () => void; emphasis?: boolean }) {
  const Element = onClick ? "button" : "div";
  return <Element onClick={onClick} className={`group rounded-2xl border p-5 text-left transition ${onClick ? "focus-ring hover:-translate-y-0.5 hover:border-white/20" : ""} ${emphasis ? "border-emerald-400/25 bg-emerald-400/[0.065]" : "border-white/[0.08] bg-white/[0.025]"}`}><div className="flex items-center justify-between"><p className="text-[10px] font-medium uppercase tracking-[0.13em] text-zinc-500">{label}</p><Icon className={`size-4 ${emphasis ? "text-emerald-300" : "text-zinc-600"}`}/></div><p className="mt-4 text-3xl font-semibold tracking-[-0.04em] text-zinc-50">{value}</p><div className="mt-1.5 flex items-center justify-between gap-2"><p className="text-xs leading-5 text-zinc-500">{detail}</p>{onClick ? <ChevronRight className="size-3.5 shrink-0 text-zinc-700 group-hover:text-zinc-300"/> : null}</div></Element>;
}

function Select({ label, value, options, onChange }: { label: string; value?: string; options: string[]; onChange: (value: string) => void }) {
  return <label><span className="mb-1.5 block text-[10px] font-medium uppercase tracking-[0.13em] text-zinc-500">{label}</span><select value={value ?? ""} onChange={(event) => onChange(event.target.value)} className="focus-ring h-10 w-full rounded-lg border border-white/10 bg-[#11151a] px-2.5 text-xs text-zinc-200 outline-none"><option value="">All</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
}

type InsightCall = ConversationInsights["highlights"][number];

function ConversationCard({ call, onOpen, compact = false }: { call: InsightCall; onOpen: () => void; compact?: boolean }) {
  return <button onClick={onOpen} className="focus-ring group w-full rounded-xl border border-white/[0.08] bg-white/[0.022] p-4 text-left transition hover:border-white/[0.16] hover:bg-white/[0.04]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-zinc-100">{call.prospect_name}</p><p className="mt-1 truncate text-xs text-zinc-500">{call.job_title || "Title unavailable"} at {call.account_name}</p></div><span className={`shrink-0 rounded-md border px-2 py-1 text-[10px] ${CATEGORY_STYLE[call.analysis.category]}`}>{call.analysis.category}</span></div><p className={`mt-3 text-xs leading-5 text-zinc-300 ${compact ? "line-clamp-3" : "line-clamp-4"}`}>{call.call_notes?.trim() || "No call notes were recorded."}</p><div className="mt-3 flex flex-wrap gap-1.5">{call.analysis.reasons.slice(0, compact ? 2 : 4).map((reason) => <span key={reason} className="rounded-md bg-white/[0.045] px-2 py-1 text-[10px] text-zinc-500">{reason}</span>)}</div><div className="mt-4 border-t border-white/[0.06] pt-3"><p className="text-[10px] font-medium uppercase tracking-[0.1em] text-zinc-600">Recommended next step</p><p className="mt-1.5 text-xs leading-5 text-zinc-400">{call.analysis.recommendedAction}</p></div><div className="mt-3 flex items-center justify-between text-[10px] text-zinc-600"><span>{duration(call.duration_seconds ?? 0)} | {call.outcome || "Outcome missing"}</span><span className="inline-flex items-center gap-1 text-zinc-400 group-hover:text-zinc-100">Call details <ArrowUpRight className="size-3"/></span></div></button>;
}

export function ConversationInsightsDashboard() {
  const [filters, setFilters] = useState<ReportFilters>(EMPTY_FILTERS);
  const [report, setReport] = useState<ConversationInsights | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [preset, setPreset] = useState("all");
  const [category, setCategory] = useState<ConversationCategory | "All">("All");
  const [search, setSearch] = useState("");
  const [drilldown, setDrilldown] = useState<Drilldown | null>(null);

  const query = useMemo(() => { const params = new URLSearchParams(); for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value); return params.toString(); }, [filters]);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError("");
    fetch(`/api/conversation-insights${query ? `?${query}` : ""}`, { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not load conversation insights."); setReport(body); }).catch((reason) => { if (reason.name !== "AbortError") setError(reason instanceof Error ? reason.message : "Could not load conversation insights."); }).finally(() => setLoading(false));
    return () => controller.abort();
  }, [query]);

  const open = useCallback((title: string, description: string, scope: Drilldown["scope"], value?: string) => setDrilldown({ title, description, scope, value }), []);
  const updateFilter = (key: keyof ReportFilters, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  const applyPreset = (value: string) => { setPreset(value); if (value === "all") return setFilters((current) => ({ ...current, from: undefined, to: undefined })); if (value === "custom" || !report?.sourceRange?.max) return; const maxDay = dayInIst(report.sourceRange.max); const days = value === "7d" ? 7 : value === "14d" ? 14 : 30; setFilters((current) => ({ ...current, from: subtractDays(maxDay, days - 1), to: maxDay })); };
  const clearFilters = () => { setFilters(EMPTY_FILTERS); setPreset("all"); };
  const visibleHighlights = useMemo(() => { if (!report) return []; const term = search.trim().toLowerCase(); return report.highlights.filter((call) => (category === "All" || call.analysis.category === category) && (!term || `${call.prospect_name} ${call.account_name} ${call.job_title} ${call.call_notes} ${call.analysis.reasons.join(" ")}`.toLowerCase().includes(term))); }, [report, category, search]);

  if (!report && loading) return <div className="space-y-5"><div className="h-36 animate-pulse rounded-2xl bg-white/[0.035]"/><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-white/[0.035]"/>)}</div><div className="h-96 animate-pulse rounded-2xl bg-white/[0.035]"/></div>;
  if (error) return <div className="rounded-2xl border border-rose-400/20 bg-rose-400/[0.06] p-8 text-sm text-rose-200">{error}</div>;
  if (!report) return null;

  const activeFilterCount = Object.values(filters).filter(Boolean).length;
  const maxObjection = Math.max(...report.objections.map((item) => item.calls), 1);
  const maxTopic = Math.max(...report.topics.map((item) => item.calls), 1);
  const period = filters.from || filters.to ? `${filters.from ?? "Start"} to ${filters.to ?? "Latest"}` : "All recorded activity";

  return <div className="conversation-insights relative space-y-5 pb-12">
    <header className="flex flex-col gap-5 py-2 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><Link href="/call-report" className="focus-ring mb-4 inline-flex items-center gap-1.5 text-xs text-zinc-500 transition hover:text-zinc-200"><ArrowLeft className="size-3.5"/>Back to Call Report</Link><div className="mb-3 text-[11px] font-medium uppercase tracking-[0.16em] text-emerald-300/80">Conversation insights</div><h1 className="text-3xl font-semibold tracking-[-0.05em] text-white md:text-4xl">Find the calls worth acting on.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Deterministic analysis of connected-call notes, follow-up signals, objections, conversation depth, and next-action coverage. No model usage or token cost.</p></div><div className="flex items-center gap-2 text-xs text-zinc-500"><RefreshCw className={`size-3.5 ${loading ? "animate-spin" : ""}`}/><span>Imported {report.latestImport?.created_at ? dateTime(report.latestImport.created_at) : "Not available"}</span></div></header>

    <div className="z-20 rounded-2xl border border-white/10 bg-[#0a0d11]/95 p-3 shadow-[0_18px_50px_rgba(0,0,0,.3)] backdrop-blur-xl lg:sticky lg:top-0"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-medium text-zinc-300"><Filter className="size-3.5"/>Filters{activeFilterCount ? <span className="rounded-full bg-emerald-400/10 px-2 py-0.5 text-[10px] text-emerald-300">{activeFilterCount} active</span> : null}</div>{activeFilterCount ? <button onClick={clearFilters} className="focus-ring inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs text-zinc-400 hover:bg-white/5 hover:text-white"><X className="size-3.5"/>Clear</button> : null}</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-7"><label><span className="mb-1.5 block text-[10px] font-medium uppercase tracking-[0.13em] text-zinc-500">Period</span><select value={preset} onChange={(event) => applyPreset(event.target.value)} className="focus-ring h-10 w-full rounded-lg border border-white/10 bg-[#11151a] px-2.5 text-xs text-zinc-200 outline-none"><option value="all">All activity</option><option value="7d">Last 7 days</option><option value="14d">Last 14 days</option><option value="30d">Last 30 days</option><option value="custom">Custom range</option></select></label><label><span className="mb-1.5 block text-[10px] font-medium uppercase tracking-[0.13em] text-zinc-500">From</span><input type="date" value={filters.from ?? ""} onInput={(event) => { setPreset("custom"); updateFilter("from", event.currentTarget.value); }} className="call-report-date focus-ring h-10 w-full rounded-lg border border-zinc-300 bg-zinc-100 px-2.5 text-xs font-medium text-zinc-950 outline-none"/></label><label><span className="mb-1.5 block text-[10px] font-medium uppercase tracking-[0.13em] text-zinc-500">To</span><input type="date" value={filters.to ?? ""} onInput={(event) => { setPreset("custom"); updateFilter("to", event.currentTarget.value); }} className="call-report-date focus-ring h-10 w-full rounded-lg border border-zinc-300 bg-zinc-100 px-2.5 text-xs font-medium text-zinc-950 outline-none"/></label><Select label="Campaign" value={filters.callSource} options={report.options.callSources} onChange={(value) => updateFilter("callSource", value)}/><Select label="Persona" value={filters.persona} options={report.options.personas} onChange={(value) => updateFilter("persona", value)}/><Select label="Industry" value={filters.industry} options={report.options.industries} onChange={(value) => updateFilter("industry", value)}/></div></div>

    <div className="flex items-center gap-2 px-1 text-xs text-zinc-500"><CalendarDays className="size-3.5"/><span>{period}</span></div>

    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6"><Metric label="Connected calls" value={number(report.summary.connectedCalls)} detail={`${number(report.summary.callsWithNotes)} include notes`} icon={Users} onClick={() => open("Connected calls", "All answered calls in the selected period.", "answered")}/><Metric label="Actionable signals" value={number(report.summary.actionable)} detail="Follow-up, nurture, or referral" icon={Target} emphasis/><Metric label="Follow up now" value={number(report.summary.followUpNow)} detail="Highest-priority note signals" icon={Sparkles}/><Metric label="Median duration" value={duration(report.summary.medianSeconds)} detail={`${duration(report.summary.averageSeconds)} average`} icon={Clock3}/><Metric label="Calls over 1 min" value={number(report.thresholds.find((item) => item.seconds === 60)?.calls ?? 0)} detail={`${percent(report.thresholds.find((item) => item.seconds === 60)?.share ?? 0)} of connects`} icon={MessageSquareText} onClick={() => open("Connected calls over one minute", "Answered calls lasting at least one minute.", "duration", "60")}/><Metric label="Next-action coverage" value={percent(report.summary.nextActionCoverage)} detail={`${number(report.summary.explicitNextAction)} explicit next-step signals`} icon={Mail}/></div>

    <Section title="Follow-up opportunities" detail="Notes with a request, referral, evaluation window, future timing, or explicit interest. Review the evidence before acting." action={<span className="rounded-lg border border-emerald-400/15 bg-emerald-400/[0.05] px-2.5 py-1 text-[10px] text-emerald-300">{number(report.followUps.length)} surfaced</span>}><div className="grid gap-3 p-4 lg:grid-cols-2 xl:grid-cols-3">{report.followUps.length ? report.followUps.slice(0, 9).map((call) => <ConversationCard key={call.id} call={call} onOpen={() => open(call.prospect_name, "All calls with this prospect inside the selected period.", "prospect", call.prospect_email)}/>) : <div className="col-span-full rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-zinc-500">No follow-up signals were found for this range.</div>}</div></Section>

    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Section title="Conversation duration" detail="Duration is a depth proxy, not proof of interest. Select a threshold to inspect its calls."><div className="grid grid-cols-2 gap-px bg-white/[0.07] sm:grid-cols-4">{report.thresholds.map((item) => <button key={item.seconds} onClick={() => open(`Connected calls lasting ${item.name}`, "Answered calls meeting this duration threshold.", "duration", String(item.seconds))} className="group bg-[#0d1014] p-5 text-left transition hover:bg-white/[0.04]"><div className="flex items-center justify-between"><p className="text-[11px] text-zinc-500 group-hover:text-zinc-200">{item.name}</p><ChevronRight className="size-3 text-zinc-700 group-hover:text-zinc-300"/></div><p className="mt-3 text-3xl font-semibold tracking-tight text-zinc-50">{number(item.calls)}</p><p className="mt-1 text-[10px] text-zinc-600">{percent(item.share)} of connected calls</p></button>)}</div><div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-4">{report.bands.map((band) => <div key={band.name} className="rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-3"><p className="text-[10px] text-zinc-600">{band.name}</p><p className="mono mt-2 text-lg text-zinc-300">{number(band.calls)}</p></div>)}</div></Section><Section title="Data confidence and hygiene" detail="Coverage checks that affect how much confidence to place in the insight layer."><div className="space-y-4 p-5"><div><div className="flex justify-between text-xs"><span className="text-zinc-400">Connected calls with notes</span><span className="mono text-zinc-200">{percent(report.summary.noteCoverage)}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[0.05]"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${report.summary.noteCoverage * 100}%` }}/></div></div><div><div className="flex justify-between text-xs"><span className="text-zinc-400">Explicit next-action coverage</span><span className="mono text-zinc-200">{percent(report.summary.nextActionCoverage)}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[0.05]"><div className="h-full rounded-full bg-blue-400" style={{ width: `${report.summary.nextActionCoverage * 100}%` }}/></div></div><div className="rounded-xl border border-rose-400/15 bg-rose-400/[0.04] p-4"><div className="flex items-center gap-2 text-xs text-rose-300"><ShieldAlert className="size-3.5"/>Suppression requests</div><p className="mt-2 text-2xl font-semibold">{number(report.summary.suppressionRequests)}</p><p className="mt-1 text-[10px] leading-4 text-zinc-500">Notes suggesting the contact should not receive another call.</p></div><p className="text-[10px] leading-5 text-zinc-600">This view analyzes written notes and logged duration. It does not infer tone, sentiment, or intent from audio.</p></div></Section></div>

    <div className="grid gap-5 xl:grid-cols-2"><Breakdown title="What prospects said" detail="Recurring objections and call-quality issues found in connected-call notes." rows={report.objections} max={maxObjection}/><Breakdown title="Themes in the notes" detail="Product, market, and next-step themes explicitly mentioned in the notes." rows={report.topics} max={maxTopic}/></div>

    <Section title="Interesting conversations" detail="Useful follow-up evidence and market learning. Filter by classification, then open any record for its full call history."><div className="flex flex-col gap-3 border-b border-white/[0.07] p-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-1.5">{(["All", ...report.categories.map((item) => item.name)] as const).map((name) => <button key={name} onClick={() => setCategory(name)} className={`focus-ring rounded-lg border px-2.5 py-2 text-[10px] transition ${category === name ? "border-zinc-200 bg-zinc-100 text-zinc-950" : "border-white/10 text-zinc-500 hover:text-zinc-200"}`}>{name}{name !== "All" ? ` ${report.categories.find((item) => item.name === name)?.calls ?? 0}` : ""}</button>)}</div><label className="flex h-9 min-w-72 items-center gap-2 rounded-lg border border-white/10 bg-black/20 px-3"><Search className="size-3.5 text-zinc-600"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search person, company, note or signal" className="w-full bg-transparent text-xs text-zinc-300 outline-none placeholder:text-zinc-600"/></label></div><div className="grid gap-3 p-4 lg:grid-cols-2">{visibleHighlights.slice(0, 20).map((call) => <ConversationCard compact key={call.id} call={call} onOpen={() => open(call.prospect_name, "All calls with this prospect inside the selected period.", "prospect", call.prospect_email)}/>)}</div></Section>

    <div className="grid gap-5 xl:grid-cols-2"><SegmentTable title="Campaign conversation quality" detail="Connected-call depth and actionable-note rate by campaign." rows={report.campaigns} scope="campaign" open={open}/><SegmentTable title="Persona conversation quality" detail="Connected-call depth and actionable-note rate by persona." rows={report.personas} scope="persona" open={open}/></div>

    <Section title="Longest connected calls" detail="Use these for qualitative review. Long duration can represent interest, objection handling, referral discovery, or a competitor conversation."><div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left text-xs"><thead className="bg-white/[0.025] text-[10px] uppercase tracking-[0.1em] text-zinc-500"><tr><th className="px-4 py-3 font-medium">Person</th><th className="px-3 py-3 font-medium">Company</th><th className="px-3 py-3 font-medium">Classification</th><th className="px-3 py-3 text-right font-medium">Duration</th><th className="px-3 py-3 font-medium">Call note</th><th className="px-4 py-3 text-right font-medium">Call</th></tr></thead><tbody>{report.longestCalls.map((call) => <tr key={call.id} onClick={() => open(call.prospect_name, "All calls with this prospect inside the selected period.", "prospect", call.prospect_email)} className="cursor-pointer border-t border-white/[0.055] align-top transition hover:bg-white/[0.04]"><td className="px-4 py-3"><p className="font-medium text-zinc-200">{call.prospect_name}</p><p className="mt-1 max-w-52 truncate text-[10px] text-zinc-600">{call.job_title || call.prospect_email}</p></td><td className="max-w-52 truncate px-3 py-3 text-zinc-400">{call.account_name}</td><td className="px-3 py-3"><span className={`inline-flex rounded-md border px-2 py-1 text-[10px] ${CATEGORY_STYLE[call.analysis.category]}`}>{call.analysis.category}</span></td><td className="mono px-3 py-3 text-right text-zinc-300">{duration(call.duration_seconds ?? 0)}</td><td className="max-w-96 px-3 py-3 leading-5 text-zinc-400"><p className="line-clamp-3">{call.call_notes?.trim() || "No call notes were recorded."}</p></td><td className="px-4 py-3 text-right">{call.shareable_link ? <a href={call.shareable_link} onClick={(event) => event.stopPropagation()} target="_blank" rel="noreferrer" className="focus-ring inline-flex size-8 items-center justify-center rounded-md border border-white/10 text-zinc-400 hover:text-white"><ArrowUpRight className="size-3.5"/></a> : <span className="text-zinc-700">None</span>}</td></tr>)}</tbody></table></div></Section>

    <CallDetailDrawer drilldown={drilldown} filters={filters} onClose={() => setDrilldown(null)}/>
  </div>;
}

function Breakdown({ title, detail, rows, max }: { title: string; detail: string; rows: Array<{ name: string; calls: number }>; max: number }) {
  return <Section title={title} detail={detail}><div className="space-y-2 p-4">{rows.map((item) => <div key={item.name} className="grid grid-cols-[150px_1fr_40px] items-center gap-3 rounded-lg px-2 py-2"><span className="text-xs text-zinc-400">{item.name}</span><span className="h-1.5 overflow-hidden rounded-full bg-white/[0.05]"><span className="block h-full rounded-full bg-zinc-400" style={{ width: `${Math.max(item.calls ? 4 : 0, item.calls / max * 100)}%` }}/></span><span className="mono text-right text-xs text-zinc-300">{item.calls}</span></div>)}</div></Section>;
}

function SegmentTable({ title, detail, rows, scope, open }: { title: string; detail: string; rows: ConversationInsights["campaigns"]; scope: "campaign" | "persona"; open: (title: string, description: string, scope: Drilldown["scope"], value?: string) => void }) {
  return <Section title={title} detail={detail}><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-white/[0.025] text-[10px] uppercase tracking-[0.1em] text-zinc-500"><tr><th className="px-4 py-3 font-medium">Group</th><th className="px-3 py-3 text-right font-medium">Connected</th><th className="px-3 py-3 text-right font-medium">Median</th><th className="px-3 py-3 text-right font-medium">1+ minute</th><th className="px-4 py-3 text-right font-medium">Actionable notes</th></tr></thead><tbody>{rows.map((item) => <tr key={item.name} onClick={() => open(item.name, `All calls in this ${scope} group during the selected period.`, scope, item.name)} className="cursor-pointer border-t border-white/[0.055] transition hover:bg-white/[0.04]"><td className="max-w-72 truncate px-4 py-3 font-medium text-zinc-300">{item.name}</td><td className="mono px-3 py-3 text-right text-zinc-400">{number(item.connectedCalls)}</td><td className="mono px-3 py-3 text-right text-zinc-400">{duration(item.medianSeconds)}</td><td className="mono px-3 py-3 text-right text-zinc-400">{number(item.overOneMinute)} ({percent(item.overOneMinuteRate)})</td><td className="mono px-4 py-3 text-right text-emerald-300">{number(item.actionable)} ({percent(item.actionableRate)})</td></tr>)}</tbody></table></div></Section>;
}
